# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Myno
tagline:          'Portfolio'
description:      'Making things'
url:              https://mynotaurus.github.io/
baseurl:          https://mynotaurus.github.io/

author:
  name:           'Myno'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Mynotaurus/Mynotaurus.github.io/
