# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Mynotaurus
tagline:          'Portfolio'
description:      'Idiot doing idiot things. Occasionally produces things of value.'
url:              https://mynotaurus.github.io/
baseurl:          https://mynotaurus.github.io/

author:
  name:           'Mika Stalley'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Mynotaurus/Mynotaurus.github.io/
